In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
plt.style.use('ggplot')

In [2]:
# prompt: mount google drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
file_path = '/content/drive/MyDrive/Football/archive/squad_seriea_stats.csv'

df = pd.read_csv(file_path)

In [4]:
df.head()

,Unnamed: 0,Squad,Age,Poss,Gls,Ast,G+A,G-PK,PK,PKatt,...,PrgP,Gls.1,Ast.1,G+A.1,G-PK.1,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,1,Atalanta,26.5,49.9,64,42,106,58,6,8,...,1637,1.68,1.11,2.79,1.53,1.52,1.12,2.64,1.35,2.47
1,2,Bologna,26.6,54.7,52,41,93,46,6,6,...,1366,1.37,1.08,2.45,1.21,1.15,0.83,1.98,1.04,1.87
2,3,Cremonese,26.0,42.1,35,18,53,30,5,7,...,1107,0.92,0.47,1.39,0.79,1.02,0.64,1.66,0.87,1.51
3,4,Empoli,25.3,47.3,35,20,55,33,2,2,...,1114,0.92,0.53,1.45,0.87,1.02,0.71,1.73,0.98,1.69
4,5,Fiorentina,26.5,56.1,51,37,88,47,4,6,...,1627,1.34,0.97,2.32,1.24,1.45,1.06,2.51,1.34,2.39

In [5]:
df.columns

Index(['Unnamed: 0', 'Squad', 'Age', 'Poss', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'Gls.1',
       'Ast.1', 'G+A.1', 'G-PK.1', 'xG.1', 'xAG.1', 'xG+xAG', 'npxG.1',
       'npxG+xAG.1'],
      dtype='object')

In [6]:
df.drop(['Unnamed: 0','Age', 'Poss', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt',
       'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'Gls.1', 'Ast.1',
       'G+A.1', 'G-PK.1', 'xG.1', 'xAG.1', 'xG+xAG', 'npxG.1', 'npxG+xAG.1'],
         axis=1, inplace=True)

In [7]:
df.head(20)

            Squad  Gls
0        Atalanta   64
1         Bologna   52
2       Cremonese   35
3          Empoli   35
4      Fiorentina   51
5   Hellas Verona   29
6           Inter   68
7        Juventus   56
8           Lazio   59
9           Lecce   31
10          Milan   61
11          Monza   46
12         Napoli   75
13           Roma   50
14    Salernitana   46
15      Sampdoria   23
16       Sassuolo   46
17         Spezia   29
18         Torino   41
19        Udinese   46

In [8]:
df['Gls'] = [66,53,36,37,53,31,71,56,60,33,64,48,77,50,48,24,
             47,31,42,47]
df['Gls casa'] = [38,29,15,22,30,20,37,38,32,18,41,
                  25,40,28,30,12,24,18,15,30]
df['Gls trasferta'] = df['Gls'] - df['Gls casa']

In [9]:
df['Gls conceded']= [48,49,69,49,43,59,42,33,30,46,43,52,28,
                       38,62,71,61,62,41,48]
df['Gls conc casa'] = [26,14,31,23,22,32,14,15,18,24,20,22,15,15,
                       26,28,23,30,19,20]
df['Gls conc trasf'] = df['Gls conceded'] - df['Gls conc casa']

In [10]:
#Normalization required for Poisson
df['Gls'] = df['Gls']/38
df['Gls conceded'] = df['Gls conceded']/38
df['Gls casa'] = df['Gls casa']/19
df['Gls trasferta'] = df['Gls trasferta']/19
df['Gls conc casa'] = df['Gls conc casa']/19
df['Gls conc trasf'] = df['Gls conc trasf']/19
df['Points 23/24'] = 0
df['W'] = 0
df['D'] = 0
df['L'] = 0

In [11]:
df.head(20)

,Squad,Gls,Gls casa,Gls trasferta,Gls conceded,Gls conc casa,Gls conc trasf,Points 23/24,W,D,L
0,Atalanta,1.736842,2.000000,1.473684,1.263158,1.368421,1.157895,0,0,0,0
1,Bologna,1.394737,1.526316,1.263158,1.289474,0.736842,1.842105,0,0,0,0
2,Cremonese,0.947368,0.789474,1.105263,1.815789,1.631579,2.000000,0,0,0,0
3,Empoli,0.973684,1.157895,0.789474,1.289474,1.210526,1.368421,0,0,0,0
4,Fiorentina,1.394737,1.578947,1.210526,1.131579,1.157895,1.105263,0,0,0,0
5,Hellas Verona,0.815789,1.052632,0.578947,1.552632,1.684211,1.421053,0,0,0,0
6,Inter,1.868421,1.947368,1.789474,1.105263,0.736842,1.473684,0,0,0,0
7,Juventus,1.473684,2.000000,0.947368,0.868421,0.789474,0.947368,0,0,0,0
8,Lazio,1.578947,1.684211,1.473684,0.789474,0.947368,0.631579,0,0,0,0
9,Lecce,0.868421,0.947368,0.789474,1.210526,1.263158,1.157895,0,0,0,0
10,Milan,1.684211,2.157895,1.210526,1.131579,1.052632,1.210526,0,0,0,0
11,Monza,1.263158,1.315789,1.210526,1.368421,1.157895,1.578947,0,0,0,0
12,Napoli,2.026316,2.105263,1.947368,0.736842,0.789474,0.684211,0,0,0,0
13,Roma,1.315789,1.473684,1.157895,1.000000,0.789474,1.210526,0,0,0,0
14,Salernitana,1.263158,1.578947,0.947368,1.631579,1.368421,1.894737,0,0,0,0
15,Sampdoria,0.631579,0.631579,0.631579,1.868421,1.473684,2.263158,0,0,0,0
16,Sassuolo,1.236842,1.263158,1.210526,1.605263,1.210526,2.000000,0,0,0,0
17,Spezia,0.815789,0.947368,0.684211,1.631579,1.578947,1.684211,0,0,0,0
18,Torino,1.105263,0.789474,1.421053,1.078947,1.000000,1.157895,0,0,0,0
19,Udinese,1.236842,1.578947,0.894737,1.263158,1.052632,1.473684,0,0,0,0

In [12]:
from itertools import combinations

elementi = list(range(20))  # numero giornate

combinazioni = list(combinations(elementi, 2))

# Aggiungi combinazioni invertite
for coppia in list(combinazioni):
    combinazioni.append((coppia[1], coppia[0]))

combinazioni.sort()
len(combinazioni)

380

In [13]:
fatti_subiti = df['Gls'].iloc[0] + df['Gls conceded'].iloc[1]
print(fatti_subiti)
print(df.iloc[0])
print(df.iloc[1])

3.026315789473684
Squad             Atalanta
Gls               1.736842
Gls casa               2.0
Gls trasferta     1.473684
Gls conceded      1.263158
Gls conc casa     1.368421
Gls conc trasf    1.157895
Points 23/24             0
W                        0
D                        0
L                        0
Name: 0, dtype: object
Squad              Bologna
Gls               1.394737
Gls casa          1.526316
Gls trasferta     1.263158
Gls conceded      1.289474
Gls conc casa     0.736842
Gls conc trasf    1.842105
Points 23/24             0
W                        0
D                        0
L                        0
Name: 1, dtype: object

In [14]:
import time
tempo_inizio = time.time()

In [15]:
def print_score(home,guest,goal1,goal2):
  print(f'{home} vs {guest} had the score: {goal1} - {goal2}')

In [16]:
%%capture
iterations = 1000

elenco_dataframe = []
for i in range(iterations):
    nome_dataframe = f'df_{i}'
    df_copia = df.copy()
    elenco_dataframe.append(df_copia)
    # Create variables DataFrame df_0 ... df_999
    vars()[nome_dataframe] = df_copia

for n in range(iterations):
  for i in combinazioni:
    #access to i[0] and i[1]
    idx1 = df['Gls casa'].iloc[i[0]] * df['Gls conc trasf'].iloc[i[1]]
    idx2 = df['Gls trasferta'].iloc[i[1]] * df['Gls conc casa'].iloc[i[0]]
    s_c = np.random.poisson(idx1)
    s_g = np.random.poisson(idx2)

    # -------- uncomment to print the scores ---------
    #print_score(df['Squad'].iloc[i[0]],df['Squad'].iloc[i[1]],s_c,s_g)

    if s_c > s_g :
      elenco_dataframe[n]['Points 23/24'].iloc[i[0]] += 3
      elenco_dataframe[n]['W'].iloc[i[0]] += 1
      elenco_dataframe[n]['L'].iloc[i[1]] += 1
    elif s_c == s_g :
      elenco_dataframe[n]['Points 23/24'].iloc[i[0]] += 1
      elenco_dataframe[n]['Points 23/24'].iloc[i[1]] += 1
      elenco_dataframe[n]['D'].iloc[i[0]] += 1
      elenco_dataframe[n]['D'].iloc[i[1]] += 1
    else:
      elenco_dataframe[n]['Points 23/24'].iloc[i[1]] += 3
      elenco_dataframe[n]['W'].iloc[i[1]] += 1
      elenco_dataframe[n]['L'].iloc[i[0]] += 1

In [17]:
tempo_fine = time.time()
tempo_trascorso = tempo_fine - tempo_inizio
tempo_trascorso = tempo_trascorso/60

print(f"Tempo impiegato: {tempo_trascorso} minuti")

Tempo impiegato: 9.473918974399567 minuti

I print only the first one to see if everything worked

In [18]:
df_ordinato = elenco_dataframe[0].sort_values(by='Points 23/24',ascending=False)

In [19]:
df_ordinato.head()

,Squad,Gls,Gls casa,Gls trasferta,Gls conceded,Gls conc casa,Gls conc trasf,Points 23/24,W,D,L
12,Napoli,2.026316,2.105263,1.947368,0.736842,0.789474,0.684211,90,28,6,4
8,Lazio,1.578947,1.684211,1.473684,0.789474,0.947368,0.631579,78,24,6,8
10,Milan,1.684211,2.157895,1.210526,1.131579,1.052632,1.210526,76,24,4,10
7,Juventus,1.473684,2.000000,0.947368,0.868421,0.789474,0.947368,75,23,6,9
0,Atalanta,1.736842,2.000000,1.473684,1.263158,1.368421,1.157895,68,20,8,10

In [21]:
colonna = 'Points 23/24'
indice_riga = 0
# Init count max values
# dict to keep track
conteggio_per_riga = {}

for df in elenco_dataframe:
    # idx row with max value Points
    indice_max = df[colonna].idxmax()

    if indice_max in conteggio_per_riga:
        conteggio_per_riga[indice_max] += 1
    else:
        conteggio_per_riga[indice_max] = 1

for indice_riga, conteggio in conteggio_per_riga.items():
    print(f"{df['Squad'][indice_riga]} won the league in {conteggio} DataFrames.")

Napoli won the league in 800 DataFrames.
Juventus won the league in 14 DataFrames.
Lazio won the league in 123 DataFrames.
Inter won the league in 46 DataFrames.
Milan won the league in 6 DataFrames.
Roma won the league in 2 DataFrames.
Atalanta won the league in 7 DataFrames.
Fiorentina won the league in 1 DataFrames.
Bologna won the league in 1 DataFrames.